
[package]
cairo-version = "2.12.2"
name = "sequential_1_dense_2_biasadd_readvariableop_0"
version = "0.1.0"
edition = "2024_07"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "v0.1.9" }
